"""changing athlete fields: category, academy, affiliation

Revision ID: acc37cffd791
Revises: fe6322e64412
Create Date: 2025-11-26 20:24:00.973534

"""
from typing import Sequence, Union

import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc37cffd791'
down_revision: Union[str, Sequence[str], None] = 'fe6322e64412'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athlete', sa.Column('category', sa.Date(), nullable=True))
    op.add_column('athlete', sa.Column('academy', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('athlete', sa.Column('affiliation', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_athlete_birth'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_region'), table_name='athlete')
    op.create_index(op.f('ix_athlete_academy'), 'athlete', ['academy'], unique=False)
    op.create_index(op.f('ix_athlete_category'), 'athlete', ['category'], unique=False)
    op.drop_column('athlete', 'city')
    op.drop_column('athlete', 'region')
    op.drop_column('athlete', 'birth')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athlete', sa.Column('birth', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('athlete', sa.Column('region', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('athlete', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_athlete_category'), table_name='athlete')
    op.drop_index(op.f('ix_athlete_academy'), table_name='athlete')
    op.create_index(op.f('ix_athlete_region'), 'athlete', ['region'], unique=False)
    op.create_index(op.f('ix_athlete_birth'), 'athlete', ['birth'], unique=False)
    op.drop_column('athlete', 'affiliation')
    op.drop_column('athlete', 'academy')
    op.drop_column('athlete', 'category')
    # ### end Alembic commands ###
