"""make tournament smoothcomp_id field unique

Revision ID: fe6322e64412
Revises: cd43331bdc06
Create Date: 2025-11-11 21:56:08.828621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe6322e64412'
down_revision: Union[str, Sequence[str], None] = 'cd43331bdc06'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'tournament', ['smoothcomp_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tournament', type_='unique')
    # ### end Alembic commands ###
