"""add calc_points to show points depending on activity ratio

Revision ID: d8f5e0ef96f9
Revises: 3a48a196cbf1
Create Date: 2026-01-15 15:53:37.192213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f5e0ef96f9'
down_revision: Union[str, Sequence[str], None] = '3a48a196cbf1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athlete', sa.Column('calc_points', sa.Float()))
    op.create_index(op.f('ix_athlete_calc_points'), 'athlete', ['calc_points'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_athlete_calc_points'), table_name='athlete')
    op.drop_column('athlete', 'calc_points')
    # ### end Alembic commands ###
