"""rename field affiliation [str] to activity[float] to calculate athletes activity in tournament participation

Revision ID: 3a48a196cbf1
Revises: 61abaf974fd1
Create Date: 2026-01-15 12:06:58.562501

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a48a196cbf1'
down_revision: Union[str, Sequence[str], None] = '61abaf974fd1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athlete', sa.Column('activity', sa.Float(), nullable=False))
    op.drop_column('athlete', 'affiliation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('athlete', sa.Column('affiliation', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('athlete', 'activity')
    # ### end Alembic commands ###
