"""FIX role field

Revision ID: 2e561add2e07
Revises: bd477e01b968
Create Date: 2025-09-29 14:13:35.855675

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "2e561add2e07"
down_revision: Union[str, Sequence[str], None] = "bd477e01b968"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
