"""update user models - add boolean is_admin field

Revision ID: 8caede7a3e4b
Revises: 2e561add2e07
Create Date: 2025-10-03 12:39:58.995583

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8caede7a3e4b"
down_revision: Union[str, Sequence[str], None] = "2e561add2e07"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("user", sa.Column("is_admin", sa.Boolean(), nullable=False))
    op.drop_constraint(op.f("user_email_key"), "user", type_="unique")
    op.create_index(op.f("ix_user_email"), "user", ["email"], unique=True)
    op.drop_column("user", "role")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user", sa.Column("role", sa.INTEGER(), autoincrement=False, nullable=False)
    )
    op.drop_index(op.f("ix_user_email"), table_name="user")
    op.create_unique_constraint(
        op.f("user_email_key"), "user", ["email"], postgresql_nulls_not_distinct=False
    )
    op.drop_column("user", "is_admin")
    # ### end Alembic commands ###
